#!/bin/sh

DB_NAME=`ls -1 ~/sr_experimental_data | tail -n 1`

if [ -z "$DB_NAME_ID" ]; then
  DB_NAME_ID="1"
fi

# DB_NAME=$DB_NAME_ID
# echo $DB_NAME
exec rosrun mongodb_log mongodb_log --mongodb-name $DB_NAME $@
