#!/bin/sh
# FUUUUUU!!! FUCKING TIMING SHIT!!!
sleep 5
DB_NAME=`ls -1 ~/sr_experimental_data | tail -n 1`

echo TEST
echo $DB_NAME
echo TEST_DONE
exec rosrun mongodb_log mongodb_log --mongodb-name $DB_NAME --mongodb-host=$MONGO_PORT_27017_TCP_ADDR $@
